basic_settings:
  site_title: SportKeeper - Membership Management Software
  favicon_image: /assets/img/favicon-196x196.png

header_settings:
  logo_image: /assets/img/brand/PNG_logo_for_light_backgrounds.png
  mobile_logo_image: 
  # Choose a color for your header [blue, dark, light].
  theme: light
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: basic
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: /
    - title: 'Features'
      url: '/features'     
    - title: Pricing
      url: /pricing        
    - title: 'Blog'
      url: /blog  
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

footer_settings:
  footer_tagline: SportKeeper, member management made simple.

contact_settings:
  form_action: 'https://formspree.io/f/xrgooold'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/sport_keeper_'
  instagram_url: 'https://instagram.com/sportkeepersoftware'
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: ''
  reddit_url: ''
  linkedin_url: ''

authors:
  justin:
    name: Justin
    picture: /assets/img/faces/justin.jpg
  jerem:
    name: Jerem
    picture: /assets/img/faces/jerem.jpg
  jadyn:
    name: Jadyn
    picture: /assets/img/faces/jadyn.jpg

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 